# Generated by Django 4.0.4 on 2022-05-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0002_rename_book_ыervice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ыervice',
            new_name='Service',
        ),
    ]
