# Generated by Django 4.0.4 on 2022-05-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0003_rename_ыervice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('build', models.CharField(max_length=30, verbose_name='Дом')),
                ('home', models.CharField(blank=True, max_length=5, null=True, verbose_name='Квартира')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wash.service', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
