# Generated by Django 4.0.4 on 2022-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, choices=[('08:00', '08:00'), ('10:00', '10:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('17:00', '17:00'), ('19:00', '19:00')], max_length=6, null=True, verbose_name='Время визита'),
        ),
    ]
