# Generated by Django 4.0.4 on 2022-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0005_order_phone_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(choices=[('08:00', '08:00'), ('10:00', '10:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('17:00', '17:00'), ('19:00', '19:00')], max_length=6, verbose_name='Время визита'),
        ),
    ]
